feat: implement curriculum module and service
FLuiz22/ufroad-api pull request #13
Opened 2023-11-30 00:20 UTC by mateusmf4

2023-11-30 14:29 UTC, FLuiz22 requested changes

2023-11-30 14:29 UTC, FLuiz22 commented on src/modules/Curriculum/CurriculumService.js
Faltou a função para criar uma grade

2023-11-30 14:29 UTC, FLuiz22 commented on src/modules/Curriculum/CurriculumRoutes.js
Faltou a rota post (criação de uma grade)

2023-11-30 14:32 UTC, mateusmf4 commented on src/modules/Curriculum/CurriculumService.js
Não foi pedido na #4, mas ok

2023-11-30 14:32 UTC, mateusmf4 commented on src/modules/Curriculum/CurriculumRoutes.js
Não foi pedido na #4, mas ok

2023-12-07 20:47 UTC, FLuiz22 approved these changes

2023-12-07 20:47 UTC, merged